### ISSUE TITLE
Can't pass a null reference in BeginPopupModal

### ISSUE THREAD

**Issue by NogginBops** [ImGuiNET/ImGui.NET#214]
I've found a problem where I want to call `BeginPopupModal` like this:
```c++
ImGui::BeginPopupModal(label, nullptr, flags)
```
which is possible by doing `ref Unsafe.AsRef<bool>(null)` in an unsafe context but the marshalling done in this library dereferences that reference which causes a `NullRefernceException`.

**Comment by Critical-Impact** [comment]
Would love to see a fix for this as I am running into this now. Can't really see a way around it
