### ISSUE TITLE
Button with empty string as label crashes

### ISSUE THREAD

**Issue by Shadowblitz16** [ImGuiNET/ImGui.NET#342]
This crashes...
```cs
public class Button : Pressable
{
    protected override void OnRender(float dt)
    {
        base.OnRender(dt);

        var id = (Label == "" ? " " : Label) + "###" + GetHashCode();
        if (ImGui.Button(id)) // Crashes
            Pressed = true;
    }
}
```
This is where it reaches before terminating the program.
![image](https://user-images.githubusercontent.com/2453707/181145528-865a7d41-109e-4060-8cec-395c081d1fcb.png)

**Comment by mbwilding** [comment]
What a code abortion :P
`var id = (Label == "" ? " " : Label) + "###" + GetHashCode();`

Could have label as a nullable string
`var id = $"{Label ??= " "}###{GetHashCode()}";`

I know this is unrelated but still haha.

**Comment by Shadowblitz16** [comment]
I thought the empty or null string was the problem. turns out it wasn't


> What a code abortion :P `var id = (Label == "" ? " " : Label) + "###" + GetHashCode();`
> 
> Could have 'Label' as a nullable string, also why do you want it to start with white space if Label == string.Empty? `var id = $"###{Label}{GetHashCode()}";`
