### ISSUE TITLE
using ImGuiListClipperPtr triggers AccessViolationException after upgrading to 1.89

### ISSUE THREAD

**Issue by pixtur** [ImGuiNET/ImGui.NET#401]
Hi,

after upgrading to v1.89.5 the following code causes as System.AccessViolationException:
```

  unsafe
  {
      var clipperData = new ImGuiListClipper();
      var listClipperPtr = new ImGuiListClipperPtr(&clipperData);
      listClipperPtr.Begin(items.Count, ImGui.GetTextLineHeightWithSpacing());
   }
```

Maybe I'm using the API in an unintended way, but it I assume something changed in the implementation. This could also be on the ImGui side, but I'm not good enough with C to write an example.

**Comment by zaafar** [comment]
was it working before 1.89.5?

**Comment by pixtur** [comment]
> after upgrading to 1.89

Good point I only tested 1.88.0 and 1.87.3.  v1.88 also triggers the exception. v1.87.3 works.

I know it's kind of too much work to ask for, but these were me steps to reproduce:

1. clone https://github.com/still-scene/t3/tree/dev
2. Upgrade nuget package
3. Start Editor and then open Window -> Console from Tooll's app menu.

**Comment by zaafar** [comment]
I just tested imgui.net version 1.89.4 (which points to cimgui 1.89.2) and its working fine.
Looks like it broke in the last upgrade (i.e. imgui.net version 1.89.5 which points to cimgui 1.89.5).

i will dig more and try to figure out what changed between these 2 versions that broke it...

**Comment by zaafar** [comment]
the only thing that changed was as following.
![image](https://github.com/ImGuiNET/ImGui.NET/assets/5079646/7b1f0704-e122-4a09-bfac-5c12561d008d)

**Comment by zaafar** [comment]
==debugging+fixing the issue==

-> lets go into this function
![image](https://github.com/ImGuiNET/ImGui.NET/assets/5079646/3629a00f-43d8-4113-8731-642bd0194195)

-> lets go into this function
![image](https://github.com/ImGuiNET/ImGui.NET/assets/5079646/ddc90fe0-2b62-4ea6-b5d0-67441c410d0f)

-> lets go into this cimgui (c language) function.
![image](https://github.com/ImGuiNET/ImGui.NET/assets/5079646/134f68ab-30ad-458e-8c57-5e1b08ad720b)

-> lets go into this imgui (c++ language) function.
![image](https://github.com/ImGuiNET/ImGui.NET/assets/5079646/6ff9d568-38bf-4e79-87cb-4ee98029d081)


-> looks like `Ctx` isn't initialized and it is suppose to be.

**Comment by zaafar** [comment]
==solution==
![image](https://github.com/ImGuiNET/ImGui.NET/assets/5079646/8b1d8898-637b-4d8c-8830-201a5ab6e7ca)

**Comment by zaafar** [comment]
interesting read: https://github.com/ocornut/imgui/commit/c8ad25caa6bfcb786085a76e67a7f31e61a80cb7

**Comment by zaafar** [comment]
this might be a little bit better approach.

```
            unsafe
            {
                var kkk = ImGuiNative.ImGuiListClipper_ImGuiListClipper();
                var clip = new ImGuiListClipperPtr(kkk);
                clip.Begin(ppp.Count);
            }
```

**Comment by pixtur** [comment]
Oh wow. Thanks for looking into that so quickly!
I'm not in a rush to upgrade, so I can wait until there is a final fix.

**Comment by zaafar** [comment]
the workaround is here (https://github.com/ImGuiNET/ImGui.NET/issues/401#issuecomment-1566216444) if you want to use that while waiting for a final fix.

**Comment by TheLostTree** [comment]
https://github.com/ImGuiNET/ImGui.NET/issues/393#issuecomment-1528692332
this should work also

**Comment by zaafar** [comment]
If you do that, you have to call the c++ destructor function as well. Just FYI.

**Comment by zaafar** [comment]
Closing this issue as it will be fixed automatically once imgui.net is upgraded to the latest (unreleased) version.
