### ISSUE TITLE
Method System.Numerics.Vector2 ImGuiNET.ImGui.CalcTextSize(System.String) Not Found.

### ISSUE THREAD

**Issue by gregkwaste** [ImGuiNET/ImGui.NET#418]
After upgrading from 1.88 to 189.6 I get the following error when trying to use `Imgui.CalcTextSize` :

   {"Method not found: 'System.Numerics.Vector2 ImGuiNET.ImGui.CalcTextSize(System.String)'."}

Any ideas?

**Comment by zaafar** [comment]
you may wanna re-compile the whole project. What we did going from 1.88 to 1.89+ is a backward incompatible change.
Following is the code I tested and it works fine on my side.

```

            string abc = "foo";
            var kkk = ImGui.CalcTextSize(abc);
            ImGui.Text(kkk.ToString());
```


Please share the code here so I can reproduce the issue on my side.

**Comment by zaafar** [comment]
![image](https://github.com/ImGuiNET/ImGui.NET/assets/5079646/748fab86-f871-49a3-8e7d-5f133f913217)

**Comment by gregkwaste** [comment]
Crap you are right, I was using a local imgui.net dll on one of my projects. Works as intended.
