### ISSUE TITLE
Image only displays default font image

### ISSUE THREAD

**Issue by ScottKane** [ImGuiNET/ImGui.NET#422]
No matter what texture pointer I pass in, the output just shows the default font texture.

![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/3ab67f01-d7db-4c3d-94f8-71c2d2ec5dfc)
![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/936ec0ba-66a3-47ea-a49d-8d32ac757677)
![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/f0df750a-8449-4c69-ad8f-22c959355da0)

I'm not sure what's going on here but I did notice that I get the font texture even when I send in `nint.Zero`.

**Comment by zaafar** [comment]
> I'm not sure what's going on here but I did notice that I get the font texture even when I send in nint.Zero.


Font texture is stored at zero index/location so it make sense that u get font texture when you send intptr.zero.


Now about your texture issue, have you printed the value of xyz to see if it's zero or something else?

**Comment by ScottKane** [comment]
I was using that specific method for a quick test, it is used to upload the bytes of a texture to a GPU buffer with WebGPU. The handle is actually returning 0 however the actual texture I am trying to get to render (the current swapchain view/framebuffer) with the following:

![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/fc72211a-da79-4b97-b509-dc3f60d22cd0)
![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/c26001ee-7da8-47f3-8dac-4b4fefae7ede)
![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/096b62e1-5397-4df2-88da-8f60c4f0c8f7)

I also directly loaded the bytes and took a pointer to them and still I get the font:

![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/ff5eb6a8-0930-42dd-8bb3-a440249f8fcb)
![image](https://github.com/ImGuiNET/ImGui.NET/assets/17254944/746debf1-a2f3-4676-919c-fae4f3049f2c)

**Comment by zaafar** [comment]
> I also directly loaded the bytes and took a pointer to them and still I get the font:

This is a cool example since in this example everything is clear.

so, in this example, where are you taking that byte pointer (bytes) and uploading it to the GPU device via the GPU API (directX, openGL, etc etc)?

**Comment by ScottKane** [comment]
I'm not, I simplified the code for that example to just directly load the image from embedded resources and pass a pointer directly to `ImGui.Image` which as far as I'm aware, shouldn't be producing the font image.

**Comment by zaafar** [comment]
> You basically get a texture back from the graphics device that you pass into a render pass.

I see, in that case, I don't know why it would fail from displaying the texture. Maybe go to the discord and sharing your issue over there to see if someone have solved this issue.

**Comment by ScottKane** [comment]
Ok from looking through some of the sample ImGui renderers, it looks like submitting the texture is deferred until the ImGui render. I think that might be my issue here so I will look into that. It's a bit more complicated to do with WebGPU than how it's done in Veldrid

**Comment by zaafar** [comment]
> In the second I simplified the code for that example to just directly load the image from embedded resources and pass a pointer directly to ImGui.Image which as far as I'm aware, shouldn't be producing the font image.

i did some test, i think it's an imgui feature where if the caller pass invalid pointer (invalid from imgui point of view), it just ignore that and defaults to zero (so basically font texture).

**Comment by ScottKane** [comment]
Thanks for those resources, the imgui_impl_wgpu is actually super helpful.

**Comment by ScottKane** [comment]
Ok I got it working with a test texture, my bind group had the font texture bound and never actually passed in the ImGui command buffer texture.
