### ISSUE TITLE
In the XNA example the ctrl and shift keys are not working with InputText.

### ISSUE THREAD

**Issue by LeviMooreDev** [ImGuiNET/ImGui.NET#430]
When using ctrl to copy and paste etc, the application quickly comes to a complete hold, it lags when dragging and no keyboard input. It takes some seconds before it is up to speed again and able to receive input.
When holding shift it also happens but a little slower.

**Comment by dvlcx** [comment]
Same here. The more you use ctrl+*any key* (even mouse buttons) in a row, the more lag lasts.

**Comment by dvlcx** [comment]
Fixed it by editing ImGuiRenderer.
![image](https://github.com/ImGuiNET/ImGui.NET/assets/83141508/abf85cc6-4a94-4388-8e85-1d627a965c63)

**Comment by dvlcx** [comment]
Fixed it by editing ImGuiRenderer.

**Comment by dvlcx** [comment]
Fixed it by editing ImGuiRenderer.
Replace this:
![image](https://github.com/ImGuiNET/ImGui.NET/assets/83141508/475d4c0e-831e-48d4-9219-af1df9a9745b)
With this:
![image](https://github.com/ImGuiNET/ImGui.NET/assets/83141508/b17317cd-8460-40fd-a330-e4d1d7a8f023)
Yes, right buttons will not work, but it is still better than lagging.

**Comment by zaafar** [comment]
can you make a PR? I will merge it.

**Comment by dvlcx** [comment]
#434
