### ISSUE TITLE
Problem with starting imgui.net

### ISSUE THREAD

**Issue by shykeiichi** [ImGuiNET/ImGui.NET#433]
When trying to start my monogame project with Monogame.ImGuiNet and ImGui.NET i get 

```
System.MissingMethodException: 'Method not found: 'ImGuiNET.RangePtrAccessor`1<ImGuiNET.ImDrawListPtr> ImGuiNET.ImDrawDataPtr.get_CmdListsRange()'.'
```

code:

```cs
imGuiRenderer.BeforeLayout(gameTime);

imGuiRenderer.AfterLayout();
```

it is run in the draw method

**Comment by zaafar** [comment]
Use CmdLists instead

**Comment by zaafar** [comment]
It’s not an IntPtr anymore: https://github.com/ImGuiNET/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs#L442

**Comment by shykeiichi** [comment]
Must be an outdated dependency of the monogame library ill check it out
