### ISSUE TITLE
Gamepad navigation does not work

### ISSUE THREAD

**Issue by DeltaW0x** [ImGuiNET/ImGui.NET#465]
Currently gamepad navigation does not work. Even if I manually wire a Keyboard key as a Gamepad key (`Keys.Down => ImGuiKey.GamepadDpadDown` instea of `Keys.Down => ImGuiKey.DownArrow` for example), ImGui still either ignores the input or doesn't receive it at all. Tested both on the FNA example program and the Veldrid one. As workaround I have to do the opposite of what written before, aka wiring a gamepad input as a keyboard one, but that's obviously not going to work very well for a variety of reasons

**Comment by zaafar** [comment]
>  Tested both on the FNA example program and the Veldrid one.

if you test the sample program, you are testing veldrid ... since sample programs are build on top of Veldrid.
So this is a veldrid issue rather than imgui.net issue. feel free to post it over here.

**Comment by DeltaW0x** [comment]
It an imgui.net issue, because wherever I test it, gamepad keycodes get eaten somehow, even if I literally force an always true AddKeyEvent(). It does not depend from anything else

**Comment by DeltaW0x** [comment]
I recompiled the repo instead of using nuget and it fixed itself, no idea why
