### ISSUE TITLE
ImGui not showing on my whole screen

### ISSUE THREAD

**Issue by GamingBonejon** [ImGuiNET/ImGui.NET#472]
Im having this issue with every project that uses ImGui and I cannot find the solution, I even wiped my computer and it stilled had the issue.

heres my code
program.cs
`
using ConsoleApp1;

Rend renderer = new Rend();
Thread renderThread = new Thread(new ThreadStart(renderer.Start().Wait));
renderThread.Start();
`

Rend.cs
`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ClickableTransparentOverlay;
using ImGuiNET;

namespace ConsoleApp1
{
    public class Rend : Overlay
    {
        //testing var
        bool booltest;

        protected override void Render()
        {
            ImGui.Begin("rendtest");
            ImGui.Checkbox("bool test", ref booltest);
        }
    }
}
`

1:
![Screenshot 2024-04-10 071431](https://github.com/ImGuiNET/ImGui.NET/assets/89711130/22a4cf4a-cd57-455e-b443-ddd5adc673ad)
2:
![Screenshot 2024-04-10 071437](https://github.com/ImGuiNET/ImGui.NET/assets/89711130/f8e52cae-9c36-4e5e-90b3-550c94a94863)

**Comment by zaafar** [comment]
issue is not in imgui.net library, closing issue.

**Comment by PaulGommard** [comment]
I’m facing the same issue, what’s the solution?
