### ISSUE TITLE
InputInt2, InputInt3, and InputInt4 definitions are getting generated incorrectly

### ISSUE THREAD

**Issue by proc-gen** [ImGuiNET/ImGui.NET#504]
The generator being used to convert the definitions into code is misinterpreting the integer array intended to be used into a single integer pointer.

From `definitions.json`:
``` json
"igInputInt2": [
  {
    "args": "(const char* label,int v[2],ImGuiInputTextFlags flags)",
  }
],
"igInputInt3": [
  {
    "args": "(const char* label,int v[3],ImGuiInputTextFlags flags)",
  }
],
"igInputInt4": [
  {
    "args": "(const char* label,int v[4],ImGuiInputTextFlags flags)",
  }
]
```

That results in function headers getting generated like the following in `ImGui.gen.cs` starting at line 15566:
``` c#
public static bool InputInt2(string label, ref int v){}
public static bool InputInt2(ReadOnlySpan<char> label, ref int v, ImGuiInputTextFlags flags){}
public static bool InputInt2(string label, ref int v, ImGuiInputTextFlags flags){}

public static bool InputInt3(string label, ref int v){}
public static bool InputInt3(ReadOnlySpan<char> label, ref int v, ImGuiInputTextFlags flags){}
public static bool InputInt3(string label, ref int v, ImGuiInputTextFlags flags){}

public static bool InputInt4(string label, ref int v){}
public static bool InputInt4(ReadOnlySpan<char> label, ref int v, ImGuiInputTextFlags flags){}
public static bool InputInt4(string label, ref int v, ImGuiInputTextFlags flags){}
```

The problem likely lies in how the type information is being determined from `argsT` in `ImguiDefinitions.cs`. I don't view these as highly used inputs, which is my guess as to why no one has noticed it before.

InputFloat2, InputFloat3, and InputFloat4 don't suffer from this issue.

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the code to correctly handle integer array parameters for InputInt2, InputInt3, and InputInt4 functions. This ensures that the generated C# code uses the correct parameter types (int[] instead of ref int) for these functions.

You can review changes in this commit: https://github.com/wwqwq2313/ImGuiNET-ImGui.NET-504/commit/52a29318b05b3855ca5beccb59a236a14ce78972.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by mellinoe** [comment]
The bindings are not incorrect; you can simply pass a reference to the first element of your contiguous buffer and it will work as expected. See https://github.com/ImGuiNET/ImGui.NET/issues/181.

(Ideally the bindings would use Span<int> here, but this library was developed a long time before Span existed)

**Comment by proc-gen** [comment]
Thank you! I looked through the open issues and didn't think to look at the closed ones before posting 😅
